#!/bin/bash
# ════════════════════════════════════════════════
# Lord Commander Blueprint — Bootstrap Script
# ════════════════════════════════════════════════
# Usage: ./bootstrap.sh [workspace_dir]
# Applies the Lord Commander blueprint to an OpenClaw workspace.
# Run this after the setup wizard fills in the variables.

set -e

BLUEPRINT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="${1:-$HOME/clawd}"
VARS_FILE="${BLUEPRINT_DIR}/.vars.json"

echo "🏰 Lord Commander Bootstrap"
echo "Blueprint: $BLUEPRINT_DIR"
echo "Workspace: $WORKSPACE"
echo ""

# Check if vars file exists (generated by wizard)
if [ ! -f "$VARS_FILE" ]; then
    echo "⚠️  No .vars.json found. Running interactive setup..."
    echo ""
    
    read -p "Your name: " USER_NAME
    read -p "Your timezone [UTC]: " USER_TIMEZONE
    USER_TIMEZONE="${USER_TIMEZONE:-UTC}"
    read -p "Your expertise/domain: " USER_EXPERTISE
    read -p "Agent name [Commander]: " AGENT_NAME
    AGENT_NAME="${AGENT_NAME:-Commander}"
    read -p "Agent emoji [🏰]: " AGENT_EMOJI
    AGENT_EMOJI="${AGENT_EMOJI:-🏰}"
    read -p "Personality (direct/friendly/formal) [direct]: " AGENT_PERSONALITY
    AGENT_PERSONALITY="${AGENT_PERSONALITY:-direct}"
    read -p "Git repo to watch (optional): " REPO_PATH

    cat > "$VARS_FILE" << VARJSON
{
    "USER_NAME": "$USER_NAME",
    "USER_TIMEZONE": "$USER_TIMEZONE",
    "USER_EXPERTISE": "$USER_EXPERTISE",
    "AGENT_NAME": "$AGENT_NAME",
    "AGENT_EMOJI": "$AGENT_EMOJI",
    "AGENT_PERSONALITY": "$AGENT_PERSONALITY",
    "REPO_PATH": "$REPO_PATH",
    "WORKSPACE": "$WORKSPACE"
}
VARJSON
    echo "✅ Variables saved to $VARS_FILE"
fi

# Read variables
USER_NAME=$(python3 -c "import json; print(json.load(open('$VARS_FILE'))['USER_NAME'])")
USER_TIMEZONE=$(python3 -c "import json; print(json.load(open('$VARS_FILE'))['USER_TIMEZONE'])")
USER_EXPERTISE=$(python3 -c "import json; print(json.load(open('$VARS_FILE')).get('USER_EXPERTISE',''))")
AGENT_NAME=$(python3 -c "import json; print(json.load(open('$VARS_FILE'))['AGENT_NAME'])")
AGENT_EMOJI=$(python3 -c "import json; print(json.load(open('$VARS_FILE'))['AGENT_EMOJI'])")
AGENT_PERSONALITY=$(python3 -c "import json; print(json.load(open('$VARS_FILE'))['AGENT_PERSONALITY'])")
REPO_PATH=$(python3 -c "import json; print(json.load(open('$VARS_FILE')).get('REPO_PATH',''))")

echo ""
echo "📝 Applying blueprint..."

# Create workspace dirs
mkdir -p "$WORKSPACE/skills" "$WORKSPACE/sparring/reviews"

# Apply templates with variable substitution
apply_template() {
    local src="$1"
    local dest="$2"
    
    sed -e "s|{{AGENT_NAME}}|$AGENT_NAME|g" \
        -e "s|{{AGENT_EMOJI}}|$AGENT_EMOJI|g" \
        -e "s|{{AGENT_PERSONALITY}}|$AGENT_PERSONALITY|g" \
        -e "s|{{USER_NAME}}|$USER_NAME|g" \
        -e "s|{{USER_TIMEZONE}}|$USER_TIMEZONE|g" \
        -e "s|{{USER_EXPERTISE}}|$USER_EXPERTISE|g" \
        -e "s|{{REPO_PATH}}|$REPO_PATH|g" \
        -e "s|{{WORKSPACE}}|$WORKSPACE|g" \
        "$src" > "$dest"
    
    echo "  ✅ $(basename "$dest")"
}

# Apply template files
for tmpl in SOUL.md IDENTITY.md USER.md AGENTS.md HEARTBEAT.md; do
    if [ -f "$BLUEPRINT_DIR/${tmpl}.template" ]; then
        apply_template "$BLUEPRINT_DIR/${tmpl}.template" "$WORKSPACE/$tmpl"
    fi
done

# Handle conditional blocks in SOUL.md based on personality
if [ "$AGENT_PERSONALITY" = "direct" ]; then
    sed -i '/{{#if PERSONALITY_direct}}/d; /{{\/if}}/d; /{{#if PERSONALITY_friendly}}/,/{{\/if}}/d; /{{#if PERSONALITY_formal}}/,/{{\/if}}/d' "$WORKSPACE/SOUL.md"
elif [ "$AGENT_PERSONALITY" = "friendly" ]; then
    sed -i '/{{#if PERSONALITY_friendly}}/d; /{{\/if}}/d; /{{#if PERSONALITY_direct}}/,/{{\/if}}/d; /{{#if PERSONALITY_formal}}/,/{{\/if}}/d' "$WORKSPACE/SOUL.md"
elif [ "$AGENT_PERSONALITY" = "formal" ]; then
    sed -i '/{{#if PERSONALITY_formal}}/d; /{{\/if}}/d; /{{#if PERSONALITY_direct}}/,/{{\/if}}/d; /{{#if PERSONALITY_friendly}}/,/{{\/if}}/d' "$WORKSPACE/SOUL.md"
fi

# Handle repo path conditional in AGENTS.md
if [ -z "$REPO_PATH" ]; then
    sed -i '/{{#if REPO_PATH}}/,/{{\/if}}/d' "$WORKSPACE/AGENTS.md"
else
    sed -i '/{{#if REPO_PATH}}/d; /{{\/if}}/d' "$WORKSPACE/AGENTS.md"
fi

# Copy static files
cp "$BLUEPRINT_DIR/MEMORY.md" "$WORKSPACE/MEMORY.md"
echo "  ✅ MEMORY.md (starter principles)"

# Copy skills
cp -r "$BLUEPRINT_DIR/skills/"* "$WORKSPACE/skills/" 2>/dev/null || true
echo "  ✅ Skills ($(ls "$BLUEPRINT_DIR/skills/" | wc -l) installed)"

echo ""
echo "🏰 Blueprint applied successfully!"
echo ""
echo "Files created:"
ls -1 "$WORKSPACE"/*.md 2>/dev/null | while read f; do echo "  📄 $(basename $f)"; done
echo ""
echo "Skills installed:"
ls -1 "$WORKSPACE/skills/" 2>/dev/null | while read f; do echo "  🔧 $f"; done
echo ""
echo "Next steps:"
echo "  1. Start OpenClaw: openclaw start"
echo "  2. Connect your channels (Telegram, etc.)"
echo "  3. Send /mission to test your agent"
echo ""
echo "⚔️ Your $AGENT_NAME $AGENT_EMOJI is ready for battle!"
